name: Check Project Updates

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, closed]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check Activity
        run: |
          echo "✨ Nouvelle activité détectée !"
          echo "Type: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
